// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api from "./routes/api.ts";
import * as $create from "./routes/create.tsx";
import * as $hero_name_ from "./routes/hero/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $search from "./routes/search.tsx";
import * as $CreateForm from "./islands/CreateForm.tsx";
import * as $DeleteForm from "./islands/DeleteForm.tsx";
import * as $Gallery from "./islands/Gallery.tsx";
import * as $SearchForm from "./islands/SearchForm.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api.ts": $api,
    "./routes/create.tsx": $create,
    "./routes/hero/[name].tsx": $hero_name_,
    "./routes/index.tsx": $index,
    "./routes/search.tsx": $search,
  },
  islands: {
    "./islands/CreateForm.tsx": $CreateForm,
    "./islands/DeleteForm.tsx": $DeleteForm,
    "./islands/Gallery.tsx": $Gallery,
    "./islands/SearchForm.tsx": $SearchForm,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
